---
title: "About Me"
subtitle: "Kyle Moore"
---

Hi, and welcome to my webpage. My name is Kyle Moore, and I'm originally from the modest town of Munford, Tennessee, an exurb of Memphis. I kept busy through grade school and high school with extracurriculars, starting with sports (baseball and football) before transitioning into quiz bowl and working at the locally owned grocery store. Quiz bowl was easily my favorite aspect of high school, and I'm still proud to have placed second — alongside my teammates Jason DeWitt, Reiamarie Guevarra, and Jamie King — in the regional 2012 WREG Knowledge Bowl tournament. After graduating, I spent the next six years in Oxford, Mississippi, studying computer science at Ole Miss. I chose Ole Miss in part because I fell in love with the campus during the twice-yearly quiz bowl tournaments held there (a running theme, I know; I bet you can't guess my favorite game show). Despite going in with no intention of doing so, I fell backwards into being a founding member of the Alpha Lambda chapter of Pi Kappa Phi, where I picked up leadership and social skills much needed at the time. Those skills were also sharpened during my tenure as an IT helpdesk technician for the University's School of Business Administration under Sam Hammoud. Most importantly, Ole Miss is where I met my long-term fiancée, Mimi (We've been engaged a while now — June 2020 turned out to be bad timing, and we'll get around to it one of these days). We met while we were volunteering as moderators for that same twice-yearly tournament.

After a short but enlightening master's program, I moved to Nashville, Tennessee to complete my PhD at Vanderbilt University. It was a rocky start, both because COVID hit at the end of my first year and because of limited research overlap with my first advisor, who, I must emphasize, is ultimately blameless. I soon found myself under the tutelage of Dr. Doug Fisher, who caught my interest with a tremendously inspiring seminar course called "Computation and Cognition." I had the pleasure of working with Dr. Fisher for the remainder of my program, and I thank him heartily for his patience in staying with me through numerous health complications and a semi-retirement. With his help — along with the collaboration of my ubiquitous research partner, Jesse Roberts (now an Assistant Professor at Tennessee Tech University), and more undergraduate research assistants than I can name here - I completed my PhD in the late summer of 2026.

On a more personal note, I've always been drawn to fantasy and science fiction, whether in books, movies, video games, or anything else. As with many people in artificial intelligence, that was a clear inspiration for the path I've taken. Seemingly unlike many, though, I find a strong optimism in that media, buried beneath the pessimistic portents of annihilation. I see hope that we will create a machine as capable and impressive as what nature created in us, and that we will come out the other side having made new companions and collaborators, not conquerors nor chattel. Drawing on the stories that inspired me, I believe far more in Mass Effect's Legion and Star Trek's Data than in Skynet or Hal 9000. I recognize that day is likely far off, if it is realistic at all — even given the massive leaps we've witnessed during my PhD years alone — but I see it as a goal worth striving for in a world that is increasingly wary of AI advancement on one hand and overeager to replace human workers on the other.

Some of my personal interests include:

  * Trying new restaurants
    * If you're ever in Nashville, try out Pelato, 615 Chutney, and VN Pho & Deli
  * Travelling
    * Some of my favorite trips so far:
      * New York City
      * Boston
      * San Diego
      * Los Angeles
      * Vietnam (Da Nang, Hue, and Ho Chi Minh City)
    * Some (of the many) places I hope to visit:
      * Seattle
      * Chicago
      * Tokyo
      * Ireland
      * Barcelona
  * Trivia (all kinds, [find me on LearnedLeague](https://www.learnedleague.com/profiles.php?76242))
  * Books, Movies, Anime, and Video Games (maybe link to my storygraph)
    * Favorite Book - Red Rising Series
    * Favorite Movie - The Matrix Series (yes, the whole thing. Resurrections doesn't count)
    * Favorite Anime - Yu Yu Hakusho
    * Favorite Video Game - Dragon Age: Origins
  * Group games including Dungeons and Dragons, most board games, and Texas Hold'em